{
 "title": "4.3 User Feedback",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "session_id",
    "label": "Session ID",
    "query": "SELECT DISTINCT session_id FROM chat_history ORDER BY session_id;\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of User prompts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS human_messages_count\nFROM chat_history\nWHERE message_type = 'user';\n"
    }
   ]
  },
  {
   "title": "Number of feedbacks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(feedback) FROM chat_history LIMIT 50 "
    }
   ]
  },
  {
   "title": "Positive vs negative Feedback",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    feedback, \n    COUNT(*) AS count\nFROM \n    chat_history\nWHERE \n    feedback IN ('thumps_up', 'thumps_down')\nGROUP BY \n    feedback;\n"
    }
   ]
  },
  {
   "title": "Number of User prompts over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n    date_trunc('minute', timestamp) AS minute,\n    COUNT(*) AS user_prompts_count\nFROM \n    chat_history\nWHERE \n    message_type = 'user'\nGROUP BY \n    minute\nORDER BY \n    minute;\n"
    }
   ]
  },
  {
   "title": "Negative User sessions",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "WITH negative_feedback AS (\n    SELECT \n        session_id,\n        COUNT(*) AS negative_count\n    FROM \n        chat_history\n    WHERE \n        feedback = 'thumps_down'\n    GROUP BY \n        session_id\n),\nassistant_prompts AS (\n    SELECT \n        session_id,\n        COUNT(*) AS assistant_prompt_count\n    FROM \n        chat_history\n    WHERE \n        message_type = 'assistant'\n    GROUP BY \n        session_id\n)\nSELECT \n    nf.session_id,\n    (nf.negative_count::float / ap.assistant_prompt_count::float) * 100  AS \"Negative Rating\",\n    ap.assistant_prompt_count AS \"Assistant Prompts\"\nFROM \n    negative_feedback nf\nJOIN \n    assistant_prompts ap ON nf.session_id = ap.session_id\nORDER BY \n    \"Negative Rating\" DESC\nLIMIT 5;\n"
    }
   ]
  },
  {
   "title": "Chat History for Session: ${session_id}",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT \n    date_trunc('second', timestamp) AS \"Timestamp\",\n    message_type AS \"Messanger\",\n    content AS \"Textbody\",\n    feedback AS \"Feedback\"\nFROM \n    chat_history\nWHERE \n    session_id = '$session_id'\nORDER BY \n    \"Timestamp\";\n"
    }
   ]
  }
 ]
}