{
 "title": "4.2 LLM quality Metrics",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "text_id",
    "label": "Text ID",
    "query": "SELECT DISTINCT text_id FROM llm_metrics ORDER BY text_id;\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "id:\"${text_id}\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "LLM as a Judge Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT llm_as_a_judge, COUNT(*) as count\nFROM llm_metrics\nGROUP BY llm_as_a_judge;\n"
    }
   ]
  },
  {
   "title": "LLM negative Sentiment",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT negative_llm_answer, COUNT(*) as count\nFROM llm_metrics\nGROUP BY negative_llm_answer;\n"
    }
   ]
  },
  {
   "title": "Cosine Similarity Distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT cosine_similarity_text_llm_answer FROM llm_metrics;"
    }
   ]
  }
 ]
}